services:
  webapp:
    image: "${DOCKER_IMAGE}"
    ports: 
    - 1010:80
    networks:
      - guvi
    secrets:
      - docker_credentials
networks:
  guvi:
secrets:
  docker_credentials:
    file: ./secret.txt
