services:
  webapp:
    image: parthitk/d2k:5
    ports: 
    - 80:80
    networks:
      - guvi
    #secrets:
     # - docker_credentials
networks:
  guvi:
#secrets:
 # docker_credentials:
 #   file: ./secret.txt
